### ISSUE TITLE
To JSON:API or not to JSON:API?

### ISSUE THREAD

**Issue by mostaphaRoudsari** [pollination/api#2]
The more I try to adopt the objects to follow JSON:API the more I think it is too much for what we need. In many cases, at least for our use-case, it feels like including all the data just because someone at some point may need them.

What I really liked about JSON:API is most of the items that they have included in [recommendation page](https://jsonapi.org/recommendations/) and I will try to replicate them in Pollination API otherwise let's KISS and move on. I will also follow their response and error codes as closely as possible. They are very well-thoughts and will make our lives easy. So why not!

If in the future we ended up expanding the data-models and realized JSON:API recommendations was indeed the right choice we can update all the models together. I do not think that will be the case for Pollination. 

See also:

- [How I design JSON API Responses](https://medium.com/@shazow/how-i-design-json-api-responses-71900f00f2db)
- [Making the most of JSON API](https://blog.apisyouwonthate.com/making-the-most-of-json-api-7fb51f4407aa)
- [JSON API: Your smart default](https://www.jeremiahlee.com/blog/2017/10/10/pragmatic-design-with-json-api/)
- [Let’s Stop Building APIs Around a Network Hack](https://blog.apisyouwonthate.com/lets-stop-building-apis-around-a-network-hack-9a68f7e83dd2)

**Comment by AntoineDao** [comment]
I reckon JSON API can be useful to provide homogenous serialization across all services (http based, event based etc...). It is worth considering how much this will duplicate the `CNCF Cloud Events`(https://cloudevents.io/) format in terms of metadata (status code etc...). 

As a side note, one of my other concerns with JSON API being used at this stage is I think it will lead to strong tempation to build `SQL-over-HTTP` which as noted in the article `Making the most of JSON API`:
> Avoid building a slow SQL-over-HTTP API, that appears to works for a few months, and fails horribly once your database tables are a little better stocked than your test data. Sure it’ll fulfill any query that anyone could possibly want, but it’ll do it poorly.

**Comment by mostaphaRoudsari** [comment]
NOT to JSON:API it is! Will use best practices from JSON:API only when it makes sense. Thanks @AntoineDao for the input.
