### ISSUE TITLE
generate openapi document from microservices

### ISSUE THREAD

**Issue by mostaphaRoudsari** [pollination/api#21]
With the new workflow the openapi documentation happens separately for each microservice and it will be a pain in the neck to update the api on this repo after the changes to microservices unless we set-up an automated workflow to collect and generate an updated documentation anytime that the documentation in any of the microservices is updated. As a matter of fact the SensorGrid endpoints are already outdated!

**Comment by AntoineDao** [comment]
Yep this issue makes sense. I don't think it's MVP though. Can we move it out of the project for now?

**Comment by mostaphaRoudsari** [comment]
I put it in MVP since otherwise it will be very challenging to reference other developers to a single place for the latest API documentation. Or does it something that comes right after the MVP for you?.

**Comment by AntoineDao** [comment]
It comes right after MVP for me. Things are going to change quite a bit until we have first pass of working services so I'd argue it's not very useful for other developpers to build on top of dreams and expectations rather than an actual working service 😛

**Comment by AntoineDao** [comment]
Shouldn't we setup the live linkes to existing repos now before we close this issue? 

https://github.com/pollination/api/blob/affc8bd52adb0c204b57000ef320bd47275e6621/openapimixer.py#L46-54

**Comment by mostaphaRoudsari** [comment]
Yes. I will open a new issue for that!
